# **Download Bioactivity Data using ChEMBL**

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

In [ ]:
# Install ChEMBL web service package
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (2.4.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (2.32.3)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2025.4.26)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.11/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.1.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.3.8)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.14.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.1 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 4.2 MB/s eta 0:00:00
Downloading cattrs-25.1.1-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 5.5 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.1.1 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

In [ ]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

 **Search for Target in ChEMBL**

Go to: https://www.ebi.ac.uk/chembl/

Search target protein name, e.g., "BACE1" or "Acetylcholinesterase".

Click on the most relevant result. When multiple ChEMBL entries exist for the same target,choose the most appropriate one.

1. Target Type: Prefer “Single Protein”
2. Organism: Choose Homo sapiens
3. Target Confidence Score (ChEMBL ≥27 only). If shown, prefer entries with a high confidence score (e.g., 9 or 10). This means: 9 = Direct single protein assignment, 8 or below = Less confident assignment (e.g., via homology)
4. Data Availability: Pick Entry with Most Bioactivity Data
Look under "Bioactivities" tab in the Target Report Card. Sort by “Assay type” or “Activity type” to see how many IC₅₀ records are available.
5. Assay Relevance (Optional, for advanced filtering)
Check if the assays are binding assays or functional assays.Binding (e.g., IC50) is usually better for QSAR modeling.Filter out low-quality or non-human assays if possible.

**AD Targets considered in this study**



1.  BACE1 - CHEMBL4822
2.  BuChE - CHEMBL1914
3.  AChE  - CHEMBL220
4.  GSK-3beta - CHEMBL262
5.  MAO-B  - CHEMBL2039
6.  ESR1  - CHEMBL206
7.  5-HT6 - CHEMBL3371

**Target search for Alzheimer - Beta-secretase 1, CHEMBL4822**

In [ ]:
target = new_client.target
#  Search for the target using ChEMBL ID
target_query = target.search('CHEMBL4822')
target1 = pd.DataFrame.from_dict(target_query)
target1

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Beta-secretase 1,15.0,False,CHEMBL4822,"[{'accession': 'P56817', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Beta-secretase (BACE),13.0,False,CHEMBL2111390,"[{'accession': 'Q9Y5Z0', 'component_descriptio...",PROTEIN FAMILY,9606

In [ ]:
selected_target = target1.target_chembl_id[0]
selected_target

'CHEMBL4822'

In [ ]:
# Get IC50 activity
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")
df1 = pd.DataFrame.from_dict(res)

In [ ]:
# Save raw data
df1.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_bace1_ic50.csv', index=False)

**Target search - BuChE - CHEMBL1914**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL1914')
target2 = pd.DataFrame.from_dict(target_query)
target2

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Butyrylcholinesterase,15.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Cholinesterases; ACHE & BCHE,13.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606

In [ ]:
#Select and retrieve bioactivity data for BuChE
selected_target = target2.target_chembl_id[0]
selected_target

'CHEMBL1914'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df2 = pd.DataFrame.from_dict(res)
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33968,[],CHEMBL654878,Inhibitory concentration against butyrylcholin...,B,None,None,BAO_0000190,...,Homo sapiens,Butyrylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.92
1,None,None,37562,[],CHEMBL654878,Inhibitory concentration against butyrylcholin...,B,None,None,BAO_0000190,...,Homo sapiens,Butyrylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.9
2,None,None,37566,[],CHEMBL654878,Inhibitory concentration against butyrylcholin...,B,None,None,BAO_0000190,...,Homo sapiens,Butyrylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38901,[],CHEMBL654878,Inhibitory concentration against butyrylcholin...,B,None,None,BAO_0000190,...,Homo sapiens,Butyrylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,1.0
4,None,None,41169,[],CHEMBL654878,Inhibitory concentration against butyrylcholin...,B,None,None,BAO_0000190,...,Homo sapiens,Butyrylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.2

In [ ]:
# Save raw data
df2.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_buche_ic50.csv', index=False)

**Target search - AChE - CHEMBL220**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL220')
target3 = pd.DataFrame.from_dict(target_query)
target3

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Acetylcholinesterase,15.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Cholinesterases; ACHE & BCHE,13.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606

In [ ]:
#Select and retrieve bioactivity data for AChE
selected_target = target3.target_chembl_id[0]
selected_target

'CHEMBL220'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df3 = pd.DataFrame.from_dict(res)
df3.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8

In [ ]:
# Save raw data
df3.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_ache_ic50.csv', index=False)

**Target search - GSK-3beta - CHEMBL262**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL262')
target4 = pd.DataFrame.from_dict(target_query)
target4

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Glycogen synthase kinase-3 beta,13.0,False,CHEMBL262,"[{'accession': 'P49841', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Glycogen synthase kinase-3,11.0,False,CHEMBL2095188,"[{'accession': 'P49840', 'component_descriptio...",PROTEIN FAMILY,9606
2,[],Homo sapiens,Axin-1/Glycogen synthase kinase-3 beta,9.0,False,CHEMBL3883309,"[{'accession': 'P49841', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [ ]:
#Select and retrieve bioactivity data for GSK-3 beta
selected_target = target4.target_chembl_id[0]
selected_target

'CHEMBL262'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df4 = pd.DataFrame.from_dict(res)
df4.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,105841,[],CHEMBL686321,Inhibitory activity against human glycogen syn...,B,None,None,BAO_0000190,...,Homo sapiens,Glycogen synthase kinase-3 beta,9606,None,None,IC50,uM,UO_0000065,None,0.38
1,None,None,114696,[],CHEMBL686321,Inhibitory activity against human glycogen syn...,B,None,None,BAO_0000190,...,Homo sapiens,Glycogen synthase kinase-3 beta,9606,None,None,IC50,uM,UO_0000065,None,6.92
2,None,None,118600,[],CHEMBL686321,Inhibitory activity against human glycogen syn...,B,None,None,BAO_0000190,...,Homo sapiens,Glycogen synthase kinase-3 beta,9606,None,None,IC50,uM,UO_0000065,None,0.41
3,None,None,118601,[],CHEMBL686321,Inhibitory activity against human glycogen syn...,B,None,None,BAO_0000190,...,Homo sapiens,Glycogen synthase kinase-3 beta,9606,None,None,IC50,uM,UO_0000065,None,0.16
4,None,None,118602,[],CHEMBL686321,Inhibitory activity against human glycogen syn...,B,None,None,BAO_0000190,...,Homo sapiens,Glycogen synthase kinase-3 beta,9606,None,None,IC50,uM,UO_0000065,None,250.0

In [ ]:
# Save raw data
df4.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_GSK-3beta_ic50.csv', index=False)

**Target search - MAO-B - CHEMBL2039**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL2039')
target5 = pd.DataFrame.from_dict(target_query)
target5

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Monoamine oxidase B,14.0,False,CHEMBL2039,"[{'accession': 'P27338', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Monoamine oxidase,12.0,False,CHEMBL2095205,"[{'accession': 'P21397', 'component_descriptio...",PROTEIN FAMILY,9606

In [ ]:
#Select and retrieve bioactivity data for MAO-B
selected_target = target5.target_chembl_id[0]
selected_target

'CHEMBL2039'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df5 = pd.DataFrame.from_dict(res)
df5.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,184069,[],CHEMBL706869,Compound was tested for inhibition of monoamin...,B,None,None,BAO_0000190,...,Homo sapiens,Monoamine oxidase B,9606,None,None,IC50,uM,UO_0000065,None,1000.0
1,None,None,185443,[],CHEMBL706869,Compound was tested for inhibition of monoamin...,B,None,None,BAO_0000190,...,Homo sapiens,Monoamine oxidase B,9606,None,None,IC50,uM,UO_0000065,None,1000.0
2,None,None,185700,[],CHEMBL734179,Inhibitory concentration against Monoamine oxi...,B,None,None,BAO_0000190,...,Homo sapiens,Monoamine oxidase B,9606,None,None,IC50,nM,UO_0000065,None,18.0
3,None,None,187020,[],CHEMBL734178,Inhibitory concentration against Monoamine oxi...,B,None,None,BAO_0000190,...,Homo sapiens,Monoamine oxidase B,9606,None,None,IC50,nM,UO_0000065,None,9.0
4,None,None,188355,[],CHEMBL734179,Inhibitory concentration against Monoamine oxi...,B,None,None,BAO_0000190,...,Homo sapiens,Monoamine oxidase B,9606,None,None,IC50,nM,UO_0000065,None,4.4

In [ ]:
# Save raw data
df5.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_mao-b_ic50.csv', index=False)

**Target search - ESR1 - CHEMBL206**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL206')
target6 = pd.DataFrame.from_dict(target_query)
target6

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Estrogen receptor alpha,11.0,False,CHEMBL206,"[{'accession': 'P03372', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Estrogen receptor,7.0,False,CHEMBL2093866,"[{'accession': 'Q92731', 'component_descriptio...",PROTEIN FAMILY,9606
2,[],Homo sapiens,Estrogen receptor/E3 ubiquitin-protein ligase ...,5.0,False,CHEMBL4523721,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
3,[],Homo sapiens,Baculoviral IAP repeat-containing protein 2/Es...,4.0,False,CHEMBL3885521,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN COMPLEX,9606
4,[],Homo sapiens,VHL/Estrogen receptor,1.0,False,CHEMBL4523726,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
5,[],Homo sapiens,VHL/Cullin-2/Estrogen receptor alpha,1.0,False,CHEMBL4523754,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
6,[],Homo sapiens,Protein cereblon/Estrogen receptor,0.0,False,CHEMBL4523681,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
7,[],Homo sapiens,Protein cereblon/Cullin-4A/Estrogen receptor,0.0,False,CHEMBL4523713,"[{'accession': 'P03372', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [ ]:
#Select and retrieve bioactivity data for ESR1
selected_target = target6.target_chembl_id[0]
selected_target

'CHEMBL206'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df6 = pd.DataFrame.from_dict(res)
df6.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,72003,[],CHEMBL679321,Binding affinity towards human estrogen recept...,B,None,None,BAO_0000190,...,Homo sapiens,Estrogen receptor alpha,9606,None,None,IC50,nM,UO_0000065,None,2.5
1,None,None,74062,[],CHEMBL679321,Binding affinity towards human estrogen recept...,B,None,None,BAO_0000190,...,Homo sapiens,Estrogen receptor alpha,9606,None,None,IC50,nM,UO_0000065,None,7.5
2,None,None,76289,[],CHEMBL679321,Binding affinity towards human estrogen recept...,B,None,None,BAO_0000190,...,Homo sapiens,Estrogen receptor alpha,9606,None,None,IC50,nM,UO_0000065,None,3.1
3,None,None,77402,[],CHEMBL679321,Binding affinity towards human estrogen recept...,B,None,None,BAO_0000190,...,Homo sapiens,Estrogen receptor alpha,9606,None,None,IC50,nM,UO_0000065,None,3.9
4,None,None,78475,[],CHEMBL679321,Binding affinity towards human estrogen recept...,B,None,None,BAO_0000190,...,Homo sapiens,Estrogen receptor alpha,9606,None,None,IC50,nM,UO_0000065,None,7.4

In [ ]:
# Save raw data
df6.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_esr1_ic50.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**Target search - 5-HT6 - CHEMBL3371**

In [ ]:
target = new_client.target
target_query = target.search('CHEMBL3371')
target7 = pd.DataFrame.from_dict(target_query)
target7

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Serotonin 6 (5-HT6) receptor,16.0,False,CHEMBL3371,"[{'accession': 'P50406', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Serotonin (5-HT) receptor,2.0,False,CHEMBL2096904,"[{'accession': 'P30939', 'component_descriptio...",PROTEIN FAMILY,9606

In [ ]:
#Select and retrieve bioactivity data for 5-HT6
selected_target = target7.target_chembl_id[0]
selected_target

'CHEMBL3371'

In [ ]:
# Retrieve bioactivity data
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")


df7 = pd.DataFrame.from_dict(res)
df7.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,103650,[],CHEMBL620798,Antagonistic activity towards 5-hydroxytryptam...,F,None,None,BAO_0000190,...,Homo sapiens,Serotonin 6 (5-HT6) receptor,9606,None,None,IC50,uM,UO_0000065,None,0.8
1,None,None,103652,[],CHEMBL620798,Antagonistic activity towards 5-hydroxytryptam...,F,None,None,BAO_0000190,...,Homo sapiens,Serotonin 6 (5-HT6) receptor,9606,None,None,IC50,uM,UO_0000065,None,0.3
2,None,None,884696,[],CHEMBL618092,Inhibition against human 5-hydroxytryptamine 6...,B,None,None,BAO_0000190,...,Homo sapiens,Serotonin 6 (5-HT6) receptor,9606,None,None,IC50,nM,UO_0000065,None,0.7
3,None,None,949636,[],CHEMBL618090,Inhibition of human 5-hydroxytryptamine 6 rece...,B,None,None,BAO_0000190,...,Homo sapiens,Serotonin 6 (5-HT6) receptor,9606,None,None,IC50,nM,UO_0000065,None,1350.0
4,None,None,949659,[],CHEMBL618090,Inhibition of human 5-hydroxytryptamine 6 rece...,B,None,None,BAO_0000190,...,Homo sapiens,Serotonin 6 (5-HT6) receptor,9606,None,None,IC50,nM,UO_0000065,None,427.0

In [ ]:
# Save raw data
df7.to_csv('/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/raw_5-HT6_ic50.csv', index=False)